### ===== Login as MEMBER =====
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "secureuser",
  "password": "123456"
}

> {%
    client.global.set("memberToken", response.body.token);
%}

### ===== MEMBER tries to access ADMIN endpoint =====
GET http://localhost:8080/users
Authorization: Bearer {{memberToken}}

### ===== Login as ADMIN =====
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "adminuser",
  "password": "123456"
}

> {%
    client.global.set("adminToken", response.body.token);
%}

### ===== ADMIN accesses ADMIN endpoint =====
GET http://localhost:8080/users
Authorization: Bearer {{adminToken}}



